# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '18'
        cache: gradle
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Run Test Server
      run: ./gradlew :FiveMinTest:bootRun >/dev/null 2>&1 &
    - name: Build Test Plugin
      run: ./gradlew :FiveMinDummyPlugin:assemblePlugin
    - name: Check Plugins
      run: ls ./plugins
    - name: Build with Gradlej
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: testCoverage -PexcludeTests="**/*nonBlocking*" --info
    - uses: actions/upload-artifact@v3
      with:
        name: log
        path: /home/runner/work/FiveMinCrawler/FiveMinCrawler/build/reports/jacoco/test/jacocoTestReport.xml
    - name: List
      run: ls -al
    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
        files: /home/runner/work/FiveMinCrawler/FiveMinCrawler/jacocoTestReport.xml
