# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      # Runs a single command using the runners shell
      - name: gradle setups
        run: ./gradlew

      - name: creates jar
        run: ./gradlew jar

      - name: creates temp directory
        run: mkdir tt

      - name: do jpackage
        run: jpackage -i ./build/lib -n FiveMinCrawler_Release --main-class MainKt --main-jar FiveMinCrawler-0.1.jar -t app-image --temp ./tt/

      - name: zip
        run: tar.exe -a -c -f release.zip FiveMinCrawler_Release
      
      - name: upload release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
